# Setup
title: Xiaowan's blogs
description: 温和却有力量，谦卑而有内涵。
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Specify the author for blog posts
author:
  name: Xiaowan Liu
  url: https://github.com/perixiaowan/
  email: peri.xiaowan@gmail.com
